use [RentaCarDb]

select *
from [dbo].[AddEquipment]
select *
from [dbo].[AirportService]
select *
from [dbo].[AspNetRoleClaims]
select *
from [dbo].[AspNetRoles]
select *
from [dbo].[AspNetUserClaims]
select *
from [dbo].[AspNetUserLogins]
select *
from [dbo].[AspNetUserRoles]
select *
from [dbo].[AspNetUsers]
select *
from [dbo].[Vehicle]